// Code generated by internal/api/gen.go — DO NOT EDIT.
// Regenerate with: go generate ./internal/api
//
// The route table in internal/api/server.go is the source of truth: request/response
// types and method names are declared there, prose comes from the comments above each
// route. Hand-written remainders live in api-manual.ts (shrinking) and api-helpers.ts.

// One transport for the whole app. Every call goes through request(), so the 401
// redirect, the error shape and the JSON handling are written once.

export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly code: string,
    message: string,
  ) {
    super(message)
  }
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const res = await fetch(path, {
    ...init,
    headers: { 'Content-Type': 'application/json', ...init.headers },
    // The session is a cookie; nothing here handles tokens.
    credentials: 'same-origin',
  })

  if (res.ok) {
    if (res.status === 204) return undefined as T
    return res.json() as Promise<T>
  }

  // Read the server's answer first, whatever the status. It always sends {code, message}, and
  // the message is written for the person who will read it — throwing it away and substituting
  // our own guess is how the sign-in page came to tell people to sign in.
  let code = 'error'
  let message = res.statusText
  try {
    const body = await res.json()
    code = body.code ?? code
    message = body.message ?? message
  } catch {
    // A non-JSON error body (a proxy's 502 page, say) — keep the status text.
  }

  // A 401 means one of two entirely different things, and conflating them was the bug:
  //
  //   unauthenticated      The session went away underneath us — expired, revoked, or the
  //                        server restarted. The page you are on is now a wall of 403s, so
  //                        bounce to /login, where "Sign in to continue." is a useful signpost.
  //
  //   invalid_credentials  The login endpoint's ANSWER. It is not a session that went away; it
  //                        is the result of the request you just made. Redirecting to the page
  //                        you are already on does nothing, and overwriting "Incorrect username
  //                        or password." with "Sign in to continue." replaces the one fact you
  //                        needed with an instruction you were already following.
  //
  // The server distinguishes them by code, so this does too. The fallback stays `unauthenticated`
  // for a 401 whose body we could not parse — a bare 401 from a proxy really is a dead session.
  if (res.status === 401 && code !== 'invalid_credentials') {
    if (code === 'error') {
      code = 'unauthenticated'
      message = 'Sign in to continue.'
    }
    if (!location.pathname.startsWith('/login')) location.assign('/login')
  }

  throw new ApiError(res.status, code, message)
}

export const api = {
  get: <T>(path: string) => request<T>(path),
  post: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: 'POST', body: body ? JSON.stringify(body) : undefined }),
  put: <T = { status: string }>(path: string, body?: unknown) =>
    request<T>(path, { method: 'PUT', body: body ? JSON.stringify(body) : undefined }),
  patch: <T = { status: string }>(path: string, body?: unknown) =>
    request<T>(path, { method: 'PATCH', body: body ? JSON.stringify(body) : undefined }),
  del: <T = { status: string }>(path: string) => request<T>(path, { method: 'DELETE' }),
}

import { manualDaffa } from './api-manual'

export { bytes, nodeQuery } from './api-helpers'
export * from './api-manual'

// ── generated types ──────────────────────────────────────────────────────────

export interface MeResponse {
  id: string
  label: string
  email: string
  kind: 'local' | 'oidc'
  roles: MeRole[]
  is_admin: boolean
  caps: Record<string, number>
  caps_by_env: Record<string, Record<string, number>>
  caps_names: string[]
}

export interface MeRole {
  name: string
  scope: 'global' | 'env'
  env_name?: string
}

export interface StatusResponse {
  status: string
}

export interface APIToken {
  id: string
  user_id: string
  user_label?: string
  name: string
  prefix: string
  expires_at?: string
  created_at: string
  last_used_at?: string
  expired?: boolean
}

export interface CreateTokenRequest {
  name?: string
  expires_days?: number
}

export interface CreatedAPIToken {
  id: string
  user_id: string
  user_label?: string
  name: string
  prefix: string
  expires_at?: string
  created_at: string
  last_used_at?: string
  expired?: boolean
  token: string
}

export interface CapabilityRegistry {
  areas: CapArea[]
  capabilities: Capability[]
}

export interface CapArea {
  ns: string
  label: string
  description: string
}

export interface Capability {
  name: string
  ns: string
  bit: number
  object: string
  mode: 'view' | 'edit' | ''
  description: string
}

export interface Environment {
  id: string
  name: string
  swarm: boolean
  status: 'online' | 'offline'
  nodes: Node[]
}

export interface Node {
  id: string
  name: string
  kind: 'local' | 'agent' | 'ssh'
  status: 'online' | 'offline'
}

export interface SSHClusterRequest {
  name?: string
  host?: string
  port?: number
  user?: string
  key_id?: string
  endpoint?: string
  host_key?: string
}

export interface SSHConnectionTest {
  ok: boolean
  error?: string
  reachable: boolean
  server_version?: string
  os?: string
  arch?: string
  host_key?: string
}

export interface CreatedCluster {
  id: string
  node_id: string
}

export interface DockerInfo {
  name: string
  server_version: string
  containers: number
  running: number
  images: number
  ncpu: number
  mem_total: number
  os: string
  arch: string
}

export interface NodeDisk {
  node_id: string
  node_name: string
  disk: DiskUsage | null
  machine?: HostDisk
}

export interface DiskUsage {
  images: Usage
  containers: Usage
  volumes: Usage
  build_cache: Usage
  total_size: number
  reclaimable: number
}

export interface Usage {
  count: number
  size: number
  reclaimable: number
}

export interface HostDisk {
  total: number
  used: number
  free: number
}

export interface RenameRequest {
  name: string
}

export interface RenameResponse {
  id: string
  name: string
}

export interface HostLogConfig {
  override: LogConfig | null
  global: LogConfig | null
  effective: LogConfig | null
}

export interface LogConfig {
  driver: string
  opts: Record<string, string>
  updated_at: string
}

export interface LogConfigRequest {
  driver?: string
  opts?: Record<string, string>
}

export interface Agent {
  id: string
  name: string
  status: 'online' | 'offline' | 'pending'
  enrolled: boolean
  version: string
  last_seen?: string
}

export interface CreateAgentRequest {
  name: string
  cluster?: string
  role?: string
  advertise_addr?: string
}

export interface NewAgent {
  id: string
  name: string
  join_token: string
  expires_in: number
}

export interface Container {
  id: string
  name: string
  image: string
  state: string
  status: string
  created: number
  ports: Port[]
  project: string
  service: string
  labels?: string[]
  node?: string
  node_id?: string
}

export interface Port {
  private: number
  public?: number
  type: string
  ip?: string
}

export interface LogLine {
  stream: 'stdout' | 'stderr'
  text: string
  task?: string
  node?: string
}

export interface Stats {
  id: string
  cpu: number
  memory: number
  mem_limit: number
  mem_pct: number
  net_rx: number
  net_tx: number
  block_read: number
  block_write: number
}

export interface DockerEvent {
  action: string
  id: string
  name: string
}

export interface Service {
  id: string
  name: string
  mode: 'replicated' | 'global'
  image: string
  tag: string
  desired: number
  running: number
  ports?: string[]
  stack?: string
  update_state?: string
  update_message?: string
  updated_at: string
}

export interface Task {
  id: string
  slot: number
  node_id: string
  desired: string
  state: string
  error?: string
  container_id?: string
  image?: string
  since: string
  node?: string
  reachable: boolean
}

export interface ClusterNode {
  node_id?: string
  name: string
  reachable: boolean
  swarm_node_id?: string
  role?: 'manager' | 'worker'
  availability?: string
  state?: string
  leader: boolean
  version?: string
  cpus?: number
  memory?: number
  in_swarm: boolean
}

export interface ScaleRequest {
  replicas: number | null
}

export interface AddNodeRequest {
  name?: string
  host?: string
  port?: number
  user?: string
  key_id?: string
  endpoint?: string
  role?: string
}

export interface AddNodeResponse {
  node_id: string
}

export interface NodeUpdateRequest {
  availability?: string
  role?: string
}

export interface SwarmInitRequest {
  advertise_addr?: string
}

export interface SwarmInitResponse {
  node_id: string
}

export interface JoinTokens {
  worker: string
  manager: string
  addr: string
}

export interface Image {
  id: string
  tags: string[]
  size: number
  created: number
  dangling: boolean
  in_use: boolean
  node?: string
  node_id?: string
}

export interface Network {
  id: string
  name: string
  driver: string
  scope: string
  internal: boolean
  containers: string[]
  system: boolean
  node?: string
  node_id?: string
}

export interface Volume {
  name: string
  driver: string
  created: string
  size: number
  used_by: string[]
  mountpoint: string
  system: boolean
  node?: string
  node_id?: string
}

export interface PruneResult {
  target: 'images' | 'containers' | 'networks' | 'volumes' | 'build-cache'
  deleted: number
  freed: number
  items?: string[]
}

export interface Stack {
  id: string
  env_id: string
  name: string
  engine: 'compose' | 'swarm'
  engine_label: string
  actions: ('up' | 'pull' | 'stop' | 'down' | 'restart' | 'down+volumes')[]
  group_name?: string
  source_kind: 'git' | 'inline'
  git_url?: string
  git_ref?: string
  git_path?: string
  git_credential_id?: string
  inline_yaml?: string
  deployed_at?: string
  deployed_commit?: string
  last_deploy_status?: string
  auto_deploy: boolean
  watch_paths?: string
  watching?: string[]
  has_secret: boolean
}

export interface StackDetail {
  stack: Stack
  services?: StackService[]
  yaml?: string
  status?: StackStatus
  warnings?: StackWarning[]
  source_error?: string
}

export interface StackService {
  name: string
  image: string
  hook?: boolean
}

export interface StackStatus {
  state: 'running' | 'partial' | 'stopped' | 'not_deployed' | 'unreachable'
  services: ServiceStatus[]
  changed: boolean
}

export interface ServiceStatus {
  name: string
  declared: string
  running?: string
  state: string
  status?: string
  container_id?: string
}

export interface StackWarning {
  service: string
  text: string
}

export interface Deployment {
  id: string
  stack_id: string
  stack_name?: string
  env_id?: string
  action: string
  status: 'running' | 'ok' | 'failed' | 'cancelled'
  engine: string
  trigger_kind: 'manual' | 'webhook' | 'rollback'
  started_by?: string
  started_by_name?: string
  exit_code?: number
  log?: string
  log_truncated?: boolean
  commit_sha?: string
  commit_subject?: string
  rollback_of?: string
  redeployable: boolean
  started_at: string
  ended_at?: string
}

export interface EnvVarItem {
  key: string
  value: string
  is_secret: boolean
}

export interface StackSecretItem {
  name: string
  content?: string
}

export interface RevealedValue {
  value: string
}

export interface StackRequest {
  env_id?: string
  node_id?: string
  name?: string
  engine?: string
  group_name?: string
  source_kind?: string
  git_url?: string
  git_ref?: string
  git_path?: string
  git_credential_id?: string
  inline_yaml?: string
}

export interface SetEnvRequest {
  vars?: EnvVarItemRequest[]
}

export interface EnvVarItemRequest {
  key?: string
  value?: string
  is_secret?: boolean
}

export interface SetSecretsRequest {
  secrets?: StackSecretItemRequest[]
}

export interface StackSecretItemRequest {
  name?: string
  content?: string
}

export interface AutoDeployRequest {
  enabled?: boolean
  watch_paths?: string
  rotate?: boolean
}

export interface AutoDeployResult {
  enabled: boolean
  secret?: string
  watch: string[]
}

export interface DeployStarted {
  deployment_id: string
  status: string
}

export interface PreviewImagesRequest {
  env_id?: string
  inline_yaml?: string
}

export interface PreviewImagesResponse {
  images: PreviewImage[]
}

export interface PreviewImage {
  ref: string
  services: string[]
  kind: string
  host?: string
  repo?: string
  tag?: string
  digest?: string
}

export interface TagCheckRequest {
  env_id?: string
  image?: string
  tag?: string
}

export interface TagCheckResponse {
  exists: boolean
  error?: string
}

export interface LatestHintRequest {
  env_id?: string
  image?: string
}

export interface LatestHintResponse {
  latest?: string
}

export interface RewriteRequest {
  env_id?: string
  inline_yaml?: string
  changes?: RewriteChangeRequest[]
}

export interface RewriteChangeRequest {
  old_ref?: string
  new_tag?: string
}

export interface RewriteResponse {
  inline_yaml: string
}

export interface VolumeSource {
  id: string
  env_id: string
  env_name?: string
  volume: string
  source_kind: string
  git_url?: string
  git_ref?: string
  git_path?: string
  git_credential_id?: string
  uid: number
  gid: number
  stack_id?: string
  stack_name?: string
  restart_targets?: string
  auto_sync: boolean
  has_webhook_secret: boolean
  synced_commit?: string
  synced_at?: string
  status: 'pending' | 'ok' | 'error'
  last_error?: string
  warnings?: string[]
  files?: VolSourceFileView[]
}

export interface VolSourceFileView {
  path: string
  content: string
  mode?: number
}

export interface VolumeSourceRequest {
  env_id?: string
  volume?: string
  source_kind?: string
  git_url?: string
  git_ref?: string
  git_path?: string
  git_credential_id?: string
  files?: VolSourceFileInputRequest[]
  uid?: number
  gid?: number
  stack_id?: string
  restart_targets?: string
  auto_sync?: boolean
  rotate?: boolean
}

export interface VolSourceFileInputRequest {
  path?: string
  content?: string
  mode?: number
}

export interface VolumeSourceSaved {
  source: VolumeSource
  webhook_secret?: string
}

export interface BackupJob {
  id: string
  env_id: string
  name: string
  container?: string
  engine: 'postgres' | 'mysql' | 'mongodb' | 'volume'
  databases?: string
  db_user?: string
  schedule?: string
  volume?: string
  stop_containers?: string
  exclude_paths?: string
  storage_id: string
  storage_name: string
  bucket: string
  prefix?: string
  encryption: 'age' | 'none'
  key_ids?: string[]
  key_names?: string[]
  enabled: boolean
  last_run?: BackupRun
}

export interface BackupRun {
  id: string
  status: 'running' | 'ok' | 'failed'
  trigger: 'manual' | 'schedule'
  bytes: number
  object_key?: string
  error?: string
  started_at: string
}

export interface Snapshot {
  key: string
  size: number
  modified: string
  encrypted: boolean
}

export interface JobRequest {
  env_id?: string
  name?: string
  container?: string
  engine?: string
  databases?: string
  db_user?: string
  db_password?: string
  schedule?: string
  volume?: string
  stop_containers?: string
  exclude_paths?: string
  storage_id?: string
  prefix?: string
  encryption?: string
  key_ids?: string[]
}

export interface StorageTarget {
  id: string
  name: string
  endpoint: string
  region: string
  bucket: string
  key_id: string
  in_use: number
}

export interface StorageRequest {
  name?: string
  endpoint?: string
  region?: string
  bucket?: string
  key_id?: string
  secret?: string
}

export interface RegistryItem {
  id: string
  name: string
  url: string
  username: string
}

export interface RegistryRequest {
  name?: string
  url?: string
  username?: string
  password?: string
  verify?: boolean | null
}

export interface RegistryCreateResponse {
  registry?: RegistryItem
  unreachable?: boolean
  reason?: string
}

export interface GitCredential {
  id: string
  name: string
  kind: 'token' | 'ssh'
  username?: string
  ssh_key_name?: string
  pinned: boolean
  in_use: number
}

export interface HostKeysResponse {
  known_hosts: string
  verified: boolean
}

export interface GitCredRequest {
  name?: string
  kind?: string
  username?: string
  token?: string
  ssh_key_id?: string
  host_key?: string
}

export interface GitTestRequest {
  url?: string
}

export interface GitTestResponse {
  ok: boolean
  error?: string
}

export interface SSHKey {
  id: string
  name: string
  algo: 'ed25519' | 'rsa' | 'ecdsa'
  public_key: string
  fingerprint: string
  has_passphrase: boolean
  in_use: number
}

export interface SSHKeyRequest {
  name?: string
  mode?: string
  algo?: string
  private_key?: string
  passphrase?: string
}

export interface CreatedSSHKey {
  id: string
  public_key: string
  fingerprint: string
}

export interface CertAuthority {
  id: string
  name: string
  subject: string
  key_algo?: string
  can_sign: boolean
  not_before: string
  not_after: string
  status: 'active' | 'next' | 'retired'
  rotates_id?: string
  overlap_until?: string
  warn_days: number
  in_use: number
  protected: boolean
  outbound_trust: boolean
}

export interface CaRequest {
  name?: string
  common_name?: string
  org?: string
  key_algo?: string
  days?: number
  cert_pem?: string
  key_pem?: string
  outbound_trust?: boolean | null
}

export interface CaUpdateRequest {
  outbound_trust?: boolean | null
}

export interface CaRotateRequest {
  name?: string
  common_name?: string
  key_algo?: string
  days?: number
  overlap_days?: number
}

export interface CaActivateRequest {
  confirm?: boolean
}

export interface Certificate {
  id: string
  name: string
  env_id?: string
  env_name?: string
  ca_id?: string
  ca_name?: string
  sans: string[]
  usages: string[]
  key_algo?: string
  not_before: string
  not_after: string
  validity_days: number
  renew_before_days: number
  status: 'ok' | 'error'
  last_error?: string
  in_use: number
  protected: boolean
}

export interface CertRequest {
  name?: string
  env_id?: string
  ca_id?: string
  sans?: string[]
  usages?: string[]
  key_algo?: string
  validity_days?: number
  renew_before_days?: number
  cert_pem?: string
  chain_pem?: string
  key_pem?: string
}

export interface CertRenewRequest {
  rotate_key?: boolean
}

export interface CertDelivery {
  id: string
  env_id: string
  env_name?: string
  cert_id?: string
  cert_name?: string
  volume: string
  uid: number
  gid: number
  traefik: boolean
  restart_targets?: string
  bundle_cas?: string[]
  mount_path: string
  status: 'pending' | 'ok' | 'error'
  last_error?: string
  synced_at?: string
  protected: boolean
}

export interface CertDeliveryRequest {
  env_id?: string
  cert_id?: string
  volume?: string
  uid?: number
  gid?: number
  traefik?: boolean
  restart_targets?: string
  bundle_cas?: string[]
}

export interface EncryptionKey {
  id: string
  name: string
  recipient: string
  source: 'generated' | 'imported'
  created_at: string
  in_use: number
}

export interface KeyRequest {
  name?: string
  recipient?: string
}

export interface CreatedKey {
  id: string
  name: string
  recipient: string
  source: string
  identity_file?: string
}

export interface Keyring {
  id: string
  name: string
  rotate_days: number
  created_at: string
  versions: KeyringVersion[]
}

export interface KeyringVersion {
  id: string
  state: 'active' | 'decrypt_only' | 'retired'
  created_at: string
}

export interface KeyringRequest {
  name?: string
  rotate_days?: number
}

export interface KeyringUpdateRequest {
  rotate_days?: number
}

export interface KeyringDelivery {
  id: string
  keyring_id: string
  keyring_name?: string
  env_id: string
  env_name?: string
  volume: string
  uid: number
  gid: number
  restart_targets?: string
  status: 'pending' | 'ok' | 'error'
  last_error?: string
  synced_at?: string
}

export interface KeyringDeliveryRequest {
  keyring_id?: string
  env_id?: string
  volume?: string
  uid?: number
  gid?: number
  restart_targets?: string
}

export interface User {
  id: string
  label: string
  username: string
  email: string
  kind: 'local' | 'oidc'
  disabled: boolean
  roles: Membership[]
  created_at: string
  last_login_at?: string
}

export interface Membership {
  role_id: string
  name: string
  is_admin: boolean
  source: 'local' | 'oidc'
  env_id?: string
  env_name?: string
}

export interface CreateUserRequest {
  username: string
  email?: string
  password: string
  grants: GrantRequest[]
}

export interface GrantRequest {
  role_id?: string
  env_id?: string
}

export interface UpdateUserRequest {
  email?: string | null
  disabled?: boolean | null
}

export interface PasswordRequest {
  password: string
}

export interface RolesRequest {
  grants?: GrantRequest[]
}

export interface Role {
  id: string
  name: string
  description: string
  caps: Record<string, number>
  cap_names: string[]
  is_admin: boolean
  builtin: boolean
  members: number
  scopable: boolean
  global_only?: string[]
}

export interface RoleRequest {
  name: string
  description?: string
  cap_names?: string[]
}

export interface Point {
  ts: string
  cpu_avg: number
  cpu_max: number
  mem_avg: number
  mem_max: number
  mem_pct: number
  mem_limit: number
}

export interface Monitor {
  id: string
  name: string
  enabled: boolean
  metric: 'cpu_pct' | 'mem_pct' | 'mem_bytes' | 'cpu_cores'
  op: string
  threshold: number
  duration_secs: number
  env_id: string
  stack: string
  container: string
  created_at: string
  updated_at: string
}

export interface Alert {
  id: string
  monitor_id: string
  monitor_name: string
  env_id: string
  container_name: string
  container_id: string
  stack: string
  state: string
  value: number
  started_at: string
  last_seen_at: string
  resolved_at: string | null
  resolve_reason: string
}

export interface MonitorRequest {
  id?: string
  name?: string
  enabled?: boolean
  metric?: string
  op?: string
  threshold?: number
  duration_secs?: number
  env_id?: string
  stack?: string
  container?: string
  created_at?: string
  updated_at?: string
}

export interface MonitorConfig {
  settings: MonitorSettings
  usage: MetricsUsage
  max_retention: number
  min_interval: number
}

export interface MonitorSettings {
  enabled: boolean
  interval_secs: number
  retention_days: number
  updated_at: string
}

export interface MetricsUsage {
  samples: number
  partitions: number
  oldest: string | null
  bytes: number
}

export interface MonitorSettingsRequest {
  enabled?: boolean
  interval_secs?: number
  retention_days?: number
}

export interface Provider {
  id: string
  slug: string
  name: string
  issuer: string
  client_id: string
  redirect_url: string
  scopes: string
  roles_claim: string
  default_role_id: string
  enabled: boolean
  has_secret: boolean
}

export interface ProviderRequest {
  slug: string
  name: string
  issuer: string
  client_id: string
  client_secret?: string
  redirect_url: string
  scopes?: string
  roles_claim?: string
  default_role_id?: string
  enabled?: boolean
}

export interface TestResult {
  ok: boolean
  message?: string
  error?: string
}

export interface RoleMapping {
  ID: string
  ProviderID: string
  ClaimValue: string
  RoleID: string
  RoleName: string
  Scope: Scope
  EnvName: string
}

export interface Scope {
  Kind: 'global' | 'env'
  ID: string
}

export interface MappingRequest {
  claim_value: string
  role_id: string
  env_id?: string
}

export interface SMTPSettings {
  host: string
  port: number
  username: string
  from_addr: string
  from_name: string
  base_url: string
  enabled: boolean
  has_password: boolean
}

export interface SmtpRequest {
  host?: string
  port?: number
  username?: string
  password?: string
  from_addr?: string
  from_name?: string
  base_url?: string
  enabled?: boolean
}

export interface NotifyEvent {
  event: string
  label: string
  description: string
  noisy: boolean
}

export interface NotifyPreviewResponse {
  subject: string
  html: string
  text: string
}

export interface FailedNotification {
  event: string
  kind: string
  to: string
  subject: string
  error: string
  at: string
}

export interface NotifyRule {
  ID: string
  Event: string
  RoleID: string
  Address: string
  ChannelID: string
  RoleName: string
  ChannelName: string
  ChannelKind: string
}

export interface RuleRequest {
  event: string
  role_id?: string
  address?: string
  channel_id?: string
}

export interface NotifyChannel {
  id: string
  kind: 'slack' | 'discord' | 'webhook'
  name: string
  enabled: boolean
}

export interface ChannelRequest {
  kind: string
  name: string
  url: string
}

export interface AuditEntry {
  at: string
  user: string
  action: string
  target: string
  outcome: 'ok' | 'error' | 'denied'
  detail: string
}

// ── generated client ─────────────────────────────────────────────────────────
// Methods migrate here from api-manual.ts as routes declare `ts:` in the route
// table. The spread order means a name collision would silently shadow the manual
// method — which is why the generator refuses to emit one (see gen.go).

export const daffa = {
  ...manualDaffa,
  logout: () => api.post<StatusResponse>('/api/auth/logout'),
  myTokens: () => api.get<APIToken[]>('/api/tokens'),
  createToken: (body: CreateTokenRequest) => api.post<CreatedAPIToken>('/api/tokens', body),
  deleteToken: (id: string) => api.del<StatusResponse>(`/api/tokens/${id}`),
  allTokens: () => api.get<APIToken[]>('/api/tokens/all'),
  capabilities: () => api.get<CapabilityRegistry>('/api/capabilities'),
  environments: () => api.get<Environment[]>('/api/clusters'),
  testClusterConnection: (body: SSHClusterRequest) =>
    api.post<SSHConnectionTest>('/api/clusters/test-connection', body),
  createCluster: (body: SSHClusterRequest) => api.post<CreatedCluster>('/api/clusters', body),
  deleteCluster: (cluster: string) => api.del<Record<string, string>>(`/api/clusters/${cluster}`),
  df: (cluster: string) => api.get<NodeDisk[]>(`/api/clusters/${cluster}/df`),
  hostLogConfig: (cluster: string) => api.get<HostLogConfig>(`/api/clusters/${cluster}/logging`),
  saveHostLogConfig: (cluster: string, body: LogConfigRequest) =>
    api.put<LogConfig>(`/api/clusters/${cluster}/logging`, body),
  clearHostLogConfig: (cluster: string) => api.del<void>(`/api/clusters/${cluster}/logging`),
  agents: () => api.get<Agent[]>('/api/agents'),
  createAgent: (body: CreateAgentRequest) => api.post<NewAgent>('/api/agents', body),
  deleteAgent: (id: string) => api.del<StatusResponse>(`/api/agents/${id}`),
  containers: (cluster: string) => api.get<Container[]>(`/api/clusters/${cluster}/containers`),
  services: (cluster: string) => api.get<Service[]>(`/api/clusters/${cluster}/services`),
  service: (cluster: string, id: string) =>
    api.get<Service>(`/api/clusters/${cluster}/services/${id}`),
  tasks: (cluster: string, id: string) =>
    api.get<Task[]>(`/api/clusters/${cluster}/services/${id}/tasks`),
  clusterNodes: (cluster: string) => api.get<ClusterNode[]>(`/api/clusters/${cluster}/nodes`),
  redeployService: (cluster: string, id: string) =>
    api.post<StatusResponse>(`/api/clusters/${cluster}/services/${id}/redeploy`),
  rollbackService: (cluster: string, id: string) =>
    api.post<StatusResponse>(`/api/clusters/${cluster}/services/${id}/rollback`),
  removeService: (cluster: string, id: string) =>
    api.del<StatusResponse>(`/api/clusters/${cluster}/services/${id}`),
  addNode: (cluster: string, body: AddNodeRequest) =>
    api.post<AddNodeResponse>(`/api/clusters/${cluster}/nodes`, body),
  updateNode: (cluster: string, id: string, body: NodeUpdateRequest) =>
    api.patch<StatusResponse>(`/api/clusters/${cluster}/nodes/${id}`, body),
  joinTokens: (cluster: string) => api.get<JoinTokens>(`/api/clusters/${cluster}/swarm/tokens`),
  images: (cluster: string) => api.get<Image[]>(`/api/clusters/${cluster}/images`),
  networks: (cluster: string) => api.get<Network[]>(`/api/clusters/${cluster}/networks`),
  volumes: (cluster: string) => api.get<Volume[]>(`/api/clusters/${cluster}/volumes`),
  prune: (cluster: string, target: 'images' | 'containers' | 'networks' | 'volumes' | 'build-cache') =>
    api.post<PruneResult>(`/api/clusters/${cluster}/prune/${target}`),
  stacks: () => api.get<Stack[]>('/api/stacks'),
  stack: (id: string) => api.get<StackDetail>(`/api/stacks/${id}`),
  stackDeployments: (id: string) => api.get<Deployment[]>(`/api/stacks/${id}/deployments`),
  stackEnv: (id: string) => api.get<EnvVarItem[]>(`/api/stacks/${id}/env`),
  stackSecrets: (id: string) => api.get<StackSecretItem[]>(`/api/stacks/${id}/secrets`),
  revealStackEnv: (id: string, key: string) =>
    api.get<RevealedValue>(`/api/stacks/${id}/env/${key}/reveal`),
  revealStackSecret: (id: string, name: string) =>
    api.get<RevealedValue>(`/api/stacks/${id}/secrets/${name}/reveal`),
  createStack: (body: StackRequest) => api.post<Stack>('/api/stacks', body),
  updateStack: (id: string, body: StackRequest) => api.put<Stack>(`/api/stacks/${id}`, body),
  setAutoDeploy: (id: string, body: AutoDeployRequest) =>
    api.put<AutoDeployResult>(`/api/stacks/${id}/autodeploy`, body),
  stackAction: (id: string, action: 'up' | 'pull' | 'stop' | 'down' | 'restart' | 'down+volumes') =>
    api.post<DeployStarted>(`/api/stacks/${id}/${action}`),
  previewComposeImages: (body: PreviewImagesRequest) =>
    api.post<PreviewImagesResponse>('/api/compose/images', body),
  checkImageTag: (body: TagCheckRequest) =>
    api.post<TagCheckResponse>('/api/compose/tag-check', body),
  latestImageTag: (body: LatestHintRequest) =>
    api.post<LatestHintResponse>('/api/compose/latest-hint', body),
  rewriteComposeImages: (body: RewriteRequest) =>
    api.post<RewriteResponse>('/api/compose/rewrite', body),
  volumeSources: () => api.get<VolumeSource[]>('/api/volume-sources'),
  createVolumeSource: (body: VolumeSourceRequest) =>
    api.post<VolumeSourceSaved>('/api/volume-sources', body),
  volumeSource: (id: string) => api.get<VolumeSource>(`/api/volume-sources/${id}`),
  updateVolumeSource: (id: string, body: VolumeSourceRequest) =>
    api.put<VolumeSourceSaved>(`/api/volume-sources/${id}`, body),
  deleteVolumeSource: (id: string) => api.del<StatusResponse>(`/api/volume-sources/${id}`),
  syncVolumeSource: (id: string) => api.post<VolumeSource>(`/api/volume-sources/${id}/sync`),
  deployment: (id: string) => api.get<Deployment>(`/api/deployments/${id}`),
  cancelDeployment: (id: string) => api.post<StatusResponse>(`/api/deployments/${id}/cancel`),
  redeploy: (id: string) => api.post<DeployStarted>(`/api/deployments/${id}/redeploy`),
  backups: () => api.get<BackupJob[]>('/api/backups'),
  backupRuns: (id: string) => api.get<BackupRun[]>(`/api/backups/${id}/runs`),
  snapshots: (id: string) => api.get<Snapshot[]>(`/api/backups/${id}/snapshots`),
  createBackup: (body: JobRequest) => api.post<Record<string, string>>('/api/backups', body),
  deleteBackup: (id: string) => api.del<Record<string, string>>(`/api/backups/${id}`),
  toggleBackup: (id: string) => api.post<Record<string, boolean>>(`/api/backups/${id}/toggle`),
  runBackup: (id: string) => api.post<StatusResponse>(`/api/backups/${id}/run`),
  storage: () => api.get<StorageTarget[]>('/api/storage'),
  createStorage: (body: StorageRequest) => api.post<Record<string, string>>('/api/storage', body),
  updateStorage: (id: string, body: StorageRequest) =>
    api.put<Record<string, string>>(`/api/storage/${id}`, body),
  deleteStorage: (id: string) => api.del<Record<string, string>>(`/api/storage/${id}`),
  registries: () => api.get<RegistryItem[]>('/api/registries'),
  createRegistry: (body: RegistryRequest) =>
    api.post<RegistryCreateResponse>('/api/registries', body),
  deleteRegistry: (id: string) => api.del<Record<string, string>>(`/api/registries/${id}`),
  gitCredentials: () => api.get<GitCredential[]>('/api/gitcreds'),
  createGitCredential: (body: GitCredRequest) =>
    api.post<Record<string, string>>('/api/gitcreds', body),
  testGitCredential: (id: string, body: GitTestRequest) =>
    api.post<GitTestResponse>(`/api/gitcreds/${id}/test`, body),
  deleteGitCredential: (id: string) => api.del<Record<string, string>>(`/api/gitcreds/${id}`),
  sshKeys: () => api.get<SSHKey[]>('/api/ssh-keys'),
  createSSHKey: (body: SSHKeyRequest) => api.post<CreatedSSHKey>('/api/ssh-keys', body),
  deleteSSHKey: (id: string) => api.del<Record<string, string>>(`/api/ssh-keys/${id}`),
  cas: () => api.get<CertAuthority[]>('/api/certs/cas'),
  createCA: (body: CaRequest) => api.post<CertAuthority>('/api/certs/cas', body),
  updateCA: (id: string, body: CaUpdateRequest) =>
    api.put<CertAuthority>(`/api/certs/cas/${id}`, body),
  rotateCA: (id: string, body: CaRotateRequest) =>
    api.post<CertAuthority>(`/api/certs/cas/${id}/rotate`, body),
  deleteCA: (id: string) => api.del<Record<string, string>>(`/api/certs/cas/${id}`),
  certs: () => api.get<Certificate[]>('/api/certs'),
  createCert: (body: CertRequest) => api.post<Certificate>('/api/certs', body),
  updateCert: (id: string, body: CertRequest) => api.put<Certificate>(`/api/certs/${id}`, body),
  deleteCert: (id: string) => api.del<Record<string, string>>(`/api/certs/${id}`),
  certDeliveries: () => api.get<CertDelivery[]>('/api/certs/deliveries'),
  createCertDelivery: (body: CertDeliveryRequest) =>
    api.post<CertDelivery>('/api/certs/deliveries', body),
  syncCertDelivery: (id: string) => api.post<CertDelivery>(`/api/certs/deliveries/${id}/sync`),
  deleteCertDelivery: (id: string) => api.del<Record<string, string>>(`/api/certs/deliveries/${id}`),
  encryptionKeys: () => api.get<EncryptionKey[]>('/api/keys'),
  createKey: (body: KeyRequest) => api.post<CreatedKey>('/api/keys', body),
  deleteKey: (id: string) => api.del<Record<string, string>>(`/api/keys/${id}`),
  keyrings: () => api.get<Keyring[]>('/api/keyrings'),
  createKeyring: (body: KeyringRequest) => api.post<Keyring>('/api/keyrings', body),
  updateKeyring: (id: string, body: KeyringUpdateRequest) =>
    api.put<Keyring>(`/api/keyrings/${id}`, body),
  rotateKeyring: (id: string) => api.post<Keyring>(`/api/keyrings/${id}/rotate`),
  retireKeyringVersion: (id: string, vid: string) =>
    api.post<Keyring>(`/api/keyrings/${id}/versions/${vid}/retire`),
  deleteKeyring: (id: string) => api.del<Record<string, string>>(`/api/keyrings/${id}`),
  keyringDeliveries: () => api.get<KeyringDelivery[]>('/api/keyrings/deliveries'),
  createKeyringDelivery: (body: KeyringDeliveryRequest) =>
    api.post<KeyringDelivery>('/api/keyrings/deliveries', body),
  syncKeyringDelivery: (id: string) =>
    api.post<KeyringDelivery>(`/api/keyrings/deliveries/${id}/sync`),
  deleteKeyringDelivery: (id: string) =>
    api.del<Record<string, string>>(`/api/keyrings/deliveries/${id}`),
  users: () => api.get<User[]>('/api/users'),
  createUser: (body: CreateUserRequest) => api.post<User>('/api/users', body),
  updateUser: (id: string, body: UpdateUserRequest) => api.patch<User>(`/api/users/${id}`, body),
  deleteUser: (id: string) => api.del<StatusResponse>(`/api/users/${id}`),
  roles: () => api.get<Role[]>('/api/roles'),
  createRole: (body: RoleRequest) => api.post<Role>('/api/roles', body),
  updateRole: (id: string, body: RoleRequest) => api.put<Role>(`/api/roles/${id}`, body),
  deleteRole: (id: string) => api.del<StatusResponse>(`/api/roles/${id}`),
  monitors: () => api.get<Monitor[]>('/api/monitors'),
  alerts: () => api.get<Alert[]>('/api/monitors/alerts'),
  createMonitor: (body: MonitorRequest) => api.post<Monitor>('/api/monitors', body),
  updateMonitor: (id: string, body: MonitorRequest) => api.put<Monitor>(`/api/monitors/${id}`, body),
  deleteMonitor: (id: string) => api.del<void>(`/api/monitors/${id}`),
  monitorConfig: () => api.get<MonitorConfig>('/api/settings/monitoring'),
  saveMonitorConfig: (body: MonitorSettingsRequest) =>
    api.put<MonitorSettings>('/api/settings/monitoring', body),
  globalLogConfig: () => api.get<LogConfig | null>('/api/settings/logging'),
  saveGlobalLogConfig: (body: LogConfigRequest) => api.put<LogConfig>('/api/settings/logging', body),
  clearGlobalLogConfig: () => api.del<void>('/api/settings/logging'),
  providers: () => api.get<Provider[]>('/api/settings/oidc'),
  createProvider: (body: ProviderRequest) => api.post<Provider>('/api/settings/oidc', body),
  updateProvider: (id: string, body: ProviderRequest) =>
    api.put<Provider>(`/api/settings/oidc/${id}`, body),
  deleteProvider: (id: string) => api.del<StatusResponse>(`/api/settings/oidc/${id}`),
  testProvider: (id: string) => api.post<TestResult>(`/api/settings/oidc/${id}/test`),
  mappings: (id: string) => api.get<RoleMapping[]>(`/api/settings/oidc/${id}/mappings`),
  createMapping: (id: string, body: MappingRequest) =>
    api.post<RoleMapping>(`/api/settings/oidc/${id}/mappings`, body),
  deleteMapping: (id: string, mapping: string) =>
    api.del<StatusResponse>(`/api/settings/oidc/${id}/mappings/${mapping}`),
  smtp: () => api.get<SMTPSettings>('/api/settings/smtp'),
  saveSmtp: (body: SmtpRequest) => api.put<SMTPSettings>('/api/settings/smtp', body),
  testSmtp: () => api.post<TestResult>('/api/settings/smtp/test'),
  notifyEvents: () => api.get<NotifyEvent[]>('/api/notifications/events'),
  previewNotification: (event: string) =>
    api.get<NotifyPreviewResponse>(`/api/notifications/preview/${event}`),
  failedNotifications: () => api.get<FailedNotification[]>('/api/notifications/failed'),
  notifyRules: () => api.get<NotifyRule[]>('/api/notifications/rules'),
  createNotifyRule: (body: RuleRequest) => api.post<NotifyRule>('/api/notifications/rules', body),
  deleteNotifyRule: (id: string) => api.del<StatusResponse>(`/api/notifications/rules/${id}`),
  notifyChannels: () => api.get<NotifyChannel[]>('/api/notifications/channels'),
  createNotifyChannel: (body: ChannelRequest) =>
    api.post<NotifyChannel>('/api/notifications/channels', body),
  testNotifyChannel: (id: string) => api.post<TestResult>(`/api/notifications/channels/${id}/test`),
  deleteNotifyChannel: (id: string) => api.del<StatusResponse>(`/api/notifications/channels/${id}`),
  audit: () => api.get<AuditEntry[]>('/api/audit'),
} as const
