// Code generated by internal/caps/gen.go — DO NOT EDIT.
//
// Run: go generate ./internal/caps

/**
 * A capability is one bit within one NAMESPACE — a functional area that carries its own mask.
 *
 * The flat mask this replaces was a single number, and it was running out. Each area now has
 * its own mask — 31 bits, the width of the INTEGER column that stores it — and a new area
 * costs one line of Go, so no area should ever be near its ceiling.
 */
export const Ns = {
  /** Containers, images, volumes and networks on a host. */
  Docker: 'docker',
  /** Stacks, and the registry and git credentials they deploy with. */
  Deploy: 'deploy',
  /** Backup jobs, and the object storage they are written to. */
  Data: 'data',
  /** Resource monitors, their alerts, and the audit log. */
  Observe: 'observe',
  /** Services, tasks and nodes on a Swarm cluster. */
  Swarm: 'swarm',
  /** Certificate authorities, the certificates they sign, and backup encryption keys. */
  Certs: 'certs',
  /** Rotatable application encryption keys, versioned so old data stays readable, delivered to hosts in volumes. */
  Keyrings: 'keyrings',
  /** Users, roles, environments and Daffa's own settings. */
  Admin: 'admin',
} as const

export type Namespace = (typeof Ns)[keyof typeof Ns]

/** What a user or a role holds: one mask per namespace. Absent means zero. */
export type CapSet = Partial<Record<Namespace, number>>

export interface Cap {
  readonly ns: Namespace
  readonly bit: number
}

export const Cap = {
  /** See containers, their logs and their stats. */
  ContainersView: { ns: Ns.Docker, bit: 1 },
  /** Start, stop, restart, kill and remove containers. */
  ContainersEdit: { ns: Ns.Docker, bit: 2 },
  /** Open a shell inside a container. The Docker socket runs as root, so this is effectively root on the host. */
  ContainersExec: { ns: Ns.Docker, bit: 4 },
  /** See images. */
  ImagesView: { ns: Ns.Docker, bit: 8 },
  /** Remove images. */
  ImagesEdit: { ns: Ns.Docker, bit: 16 },
  /** See networks. */
  NetworksView: { ns: Ns.Docker, bit: 32 },
  /** Remove networks. */
  NetworksEdit: { ns: Ns.Docker, bit: 64 },
  /** See volumes. */
  VolumesView: { ns: Ns.Docker, bit: 128 },
  /** Remove volumes. Removing a volume destroys its data. */
  VolumesEdit: { ns: Ns.Docker, bit: 256 },
  /** Bulk-delete every unused image, volume and network on a host. Irreversible and host-wide. */
  SystemPrune: { ns: Ns.Docker, bit: 512 },
  /** See stacks, their services and their deployment history. */
  StacksView: { ns: Ns.Deploy, bit: 1 },
  /** Create, deploy, cancel, roll back and remove stacks; set their environment variables, secrets and auto-deploy. */
  StacksEdit: { ns: Ns.Deploy, bit: 2 },
  /** See configured registries — never their passwords. The list is shared by every cluster. */
  RegistriesView: { ns: Ns.Deploy, bit: 4 },
  /** Add and remove registries, including their passwords. Fleet-wide. */
  RegistriesEdit: { ns: Ns.Deploy, bit: 8 },
  /** See which git credentials exist, by name — never their tokens or keys. The list is shared by every cluster. */
  GitCredsView: { ns: Ns.Deploy, bit: 16 },
  /** Add and remove git credentials, including tokens and SSH keys. Fleet-wide. */
  GitCredsEdit: { ns: Ns.Deploy, bit: 32 },
  /** See volume sources — repository, ref, subtree, live commit and sync status. */
  VolsourcesView: { ns: Ns.Deploy, bit: 64 },
  /** Create, edit, sync and delete volume sources. A sync overwrites the volume's Daffa-delivered files with the repository's. */
  VolsourcesEdit: { ns: Ns.Deploy, bit: 128 },
  /** See backup jobs and whether they are succeeding. */
  BackupsView: { ns: Ns.Data, bit: 1 },
  /** Create, edit, enable and run backup jobs. */
  BackupsEdit: { ns: Ns.Data, bit: 2 },
  /** Restore a snapshot, overwriting a live database. */
  BackupsRestore: { ns: Ns.Data, bit: 4 },
  /** Download a snapshot. It is an encrypted dump of an entire database. */
  BackupsDownload: { ns: Ns.Data, bit: 8 },
  /** See S3/R2 targets by name — never their secret keys. The list is shared by every cluster. */
  StorageView: { ns: Ns.Data, bit: 16 },
  /** Add, edit and remove S3/R2 targets, including their credentials. Fleet-wide. */
  StorageEdit: { ns: Ns.Data, bit: 32 },
  /** See resource monitors and the alerts they have raised. */
  MonitorsView: { ns: Ns.Observe, bit: 1 },
  /** Create and edit resource monitors, and change how long samples are kept. A monitor that watches every cluster requires this on every cluster. */
  MonitorsEdit: { ns: Ns.Observe, bit: 2 },
  /** Read the audit log — every privileged action anyone took, and every one they were refused. */
  AuditView: { ns: Ns.Observe, bit: 4 },
  /** See a Swarm cluster's services, their tasks and their logs. The task is where a service says why it is not running. */
  ServicesView: { ns: Ns.Swarm, bit: 1 },
  /** Scale, redeploy, roll back and remove Swarm services. On a Swarm this is also read access to every secret: you can mount any of them into a service you control and read it out of the container. */
  ServicesEdit: { ns: Ns.Swarm, bit: 2 },
  /** Drain, pause, promote and demote the machines in a Swarm, and remove them from it. Draining a node evicts every Swarm task on it. Reading the node list is clusters.view. */
  NodesEdit: { ns: Ns.Swarm, bit: 4 },
  /** Create a Swarm on a host, read its join tokens, and leave it. A join token lets anybody who has it add a machine to the cluster, so it is a credential and this is the capability that reads one. */
  SwarmEdit: { ns: Ns.Swarm, bit: 8 },
  /** See certificate authorities, certificates and their deliveries — names, SANs, expiry. Never a private key. */
  CertsView: { ns: Ns.Certs, bit: 1 },
  /** Create and upload CAs and certificates, rotate them, and deliver them to hosts. A CA Daffa holds signs certificates the whole fleet trusts — this is the power to mint one for any name. */
  CertsEdit: { ns: Ns.Certs, bit: 2 },
  /** See backup encryption keys: their names and public halves. The private halves do not exist on the server. */
  KeysView: { ns: Ns.Certs, bit: 4 },
  /** Generate and import backup encryption keys. The private half is downloaded once at generation and never stored. */
  KeysEdit: { ns: Ns.Certs, bit: 8 },
  /** See keyrings, their version timeline and their deliveries — names, states, ages, sync status. Never key material. */
  KeyringsView: { ns: Ns.Keyrings, bit: 1 },
  /** Create, rotate and retire keyrings, and deliver them to hosts. Retiring a version makes data encrypted under it unreadable to every consumer. */
  KeyringsEdit: { ns: Ns.Keyrings, bit: 2 },
  /** See the list of users and the roles they hold. */
  UsersView: { ns: Ns.Admin, bit: 1 },
  /** Create, disable and delete users, reset passwords, and grant roles. */
  UsersEdit: { ns: Ns.Admin, bit: 2 },
  /** See roles and the capabilities they carry. */
  RolesView: { ns: Ns.Admin, bit: 4 },
  /** Create and edit roles. Anyone who can edit a role can grant themselves anything in it — this is an administrative power, not a lesser one. */
  RolesEdit: { ns: Ns.Admin, bit: 8 },
  /** See identity provider and notification settings. Never secrets. */
  SettingsView: { ns: Ns.Admin, bit: 16 },
  /** Add, edit and remove identity providers, role mappings and notification rules. */
  SettingsEdit: { ns: Ns.Admin, bit: 32 },
  /** See a cluster and its disk usage. Without this, a cluster is invisible — it does not appear in the switcher at all. */
  ClustersView: { ns: Ns.Admin, bit: 64 },
  /** Rename clusters, and enroll or revoke agents. An agent brings a new machine Daffa can reach — so this is fleet-wide. */
  ClustersEdit: { ns: Ns.Admin, bit: 128 },
  /** See the default container log driver and rotation for deploys — the fleet default and any cluster override. */
  LoggingView: { ns: Ns.Admin, bit: 256 },
  /** Set a cluster's container log defaults, applied to services at their next deploy. Changing the fleet-wide default requires this globally. */
  LoggingEdit: { ns: Ns.Admin, bit: 512 },
} as const satisfies Record<string, Cap>

export type CapValue = (typeof Cap)[keyof typeof Cap]

/**
 * Does this set carry that capability?
 *
 * A cap with no bit is never satisfied, mirroring the server: a check written against something
 * that does not exist denies rather than admits.
 *
 * DO NOT rewrite the test as `(mask & cap.bit) !== 0`. It looks like the obvious spelling and it
 * is wrong, because JavaScript's bitwise operators coerce BOTH operands to 32-bit signed
 * integers before doing anything. A capability above bit 31 therefore becomes literally zero:
 *
 *     4294967296 | 0   // bit 32  ->  0
 *     mask & 0         // ->  0, so the check can NEVER pass. For anyone. Including an admin.
 *
 * That shipped, back when the mask was flat: Resource Monitors appeared in the nav (monitors.view
 * was bit 31, which survives by accident because the sign bit is still a bit) and its editor did
 * not (monitors.edit was bit 32, which does not) — so an administrator holding every capability
 * in the registry was told they could not create a monitor.
 *
 * Namespacing means no area is anywhere near bit 31 today. That is not a reason to use the
 * broken operator; it is a reason the bug would take even longer to find next time.
 */
export function hasCap(set: CapSet | undefined, cap: CapValue): boolean {
  if (!set || !cap?.bit) return false
  return (BigInt(set[cap.ns] ?? 0) & BigInt(cap.bit)) !== 0n
}
