package api

import (
	_ "embed"
	"net/http"
)

// The artifact is generated by `go generate ./internal/api`, checked in, and embedded —
// the caps.ts treatment. Serving the checked-in bytes (rather than rebuilding at boot)
// means the spec a client reads is exactly the one the repo reviewed.
//
//go:embed openapi.json
var openAPISpec []byte

// OpenAPISpec returns the embedded OpenAPI document. The CLI's `daffa openapi` dumps it
// so tooling can consume the spec without authenticating against a running server.
func OpenAPISpec() []byte { return openAPISpec }

func (s *Server) handleOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(openAPISpec)
}
