package openapi

import (
	"fmt"
	"regexp"
	"strings"
)

// BuildClient renders the whole of web/src/lib/api.ts: generated header, the transport
// preamble (verbatim — it was the handwritten file's, and it is the app's one transport),
// re-exports of the handwritten helpers and the shrinking manual remainder, the
// interfaces, and the daffa client merged over manualDaffa.
func BuildClient(ops []Op, components []*Component) (string, error) {
	var b strings.Builder
	b.WriteString(tsHeader)
	b.WriteString(tsPreamble)
	b.WriteString(tsBridge)

	b.WriteString("// ── generated types ──────────────────────────────────────────────────────────\n")
	for _, c := range components {
		b.WriteString("\n")
		b.WriteString(tsInterface(c))
	}

	b.WriteString("\n// ── generated client ─────────────────────────────────────────────────────────\n")
	b.WriteString("// Methods migrate here from api-manual.ts as routes declare `ts:` in the route\n")
	b.WriteString("// table. The spread order means a name collision would silently shadow the manual\n")
	b.WriteString("// method — which is why the generator refuses to emit one (see gen.go).\n\n")
	b.WriteString("export const daffa = {\n  ...manualDaffa,\n")
	for i := range ops {
		op := &ops[i]
		if op.TSName == "" {
			continue
		}
		m, err := tsMethod(op)
		if err != nil {
			return "", err
		}
		b.WriteString(m)
	}
	b.WriteString("} as const\n")
	return b.String(), nil
}

const tsHeader = `// Code generated by internal/api/gen.go — DO NOT EDIT.
// Regenerate with: go generate ./internal/api
//
// The route table in internal/api/server.go is the source of truth: request/response
// types and method names are declared there, prose comes from the comments above each
// route. Hand-written remainders live in api-manual.ts (shrinking) and api-helpers.ts.

`

// tsPreamble is the handwritten transport, carried verbatim from the pre-generation
// api.ts. It is template text, not generated: the 401 story in these comments was earned.
const tsPreamble = `// One transport for the whole app. Every call goes through request(), so the 401
// redirect, the error shape and the JSON handling are written once.

export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly code: string,
    message: string,
  ) {
    super(message)
  }
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const res = await fetch(path, {
    ...init,
    headers: { 'Content-Type': 'application/json', ...init.headers },
    // The session is a cookie; nothing here handles tokens.
    credentials: 'same-origin',
  })

  if (res.ok) {
    if (res.status === 204) return undefined as T
    return res.json() as Promise<T>
  }

  // Read the server's answer first, whatever the status. It always sends {code, message}, and
  // the message is written for the person who will read it — throwing it away and substituting
  // our own guess is how the sign-in page came to tell people to sign in.
  let code = 'error'
  let message = res.statusText
  try {
    const body = await res.json()
    code = body.code ?? code
    message = body.message ?? message
  } catch {
    // A non-JSON error body (a proxy's 502 page, say) — keep the status text.
  }

  // A 401 means one of two entirely different things, and conflating them was the bug:
  //
  //   unauthenticated      The session went away underneath us — expired, revoked, or the
  //                        server restarted. The page you are on is now a wall of 403s, so
  //                        bounce to /login, where "Sign in to continue." is a useful signpost.
  //
  //   invalid_credentials  The login endpoint's ANSWER. It is not a session that went away; it
  //                        is the result of the request you just made. Redirecting to the page
  //                        you are already on does nothing, and overwriting "Incorrect username
  //                        or password." with "Sign in to continue." replaces the one fact you
  //                        needed with an instruction you were already following.
  //
  // The server distinguishes them by code, so this does too. The fallback stays ` + "`unauthenticated`" + `
  // for a 401 whose body we could not parse — a bare 401 from a proxy really is a dead session.
  if (res.status === 401 && code !== 'invalid_credentials') {
    if (code === 'error') {
      code = 'unauthenticated'
      message = 'Sign in to continue.'
    }
    if (!location.pathname.startsWith('/login')) location.assign('/login')
  }

  throw new ApiError(res.status, code, message)
}

export const api = {
  get: <T>(path: string) => request<T>(path),
  post: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: 'POST', body: body ? JSON.stringify(body) : undefined }),
  put: <T = { status: string }>(path: string, body?: unknown) =>
    request<T>(path, { method: 'PUT', body: body ? JSON.stringify(body) : undefined }),
  patch: <T = { status: string }>(path: string, body?: unknown) =>
    request<T>(path, { method: 'PATCH', body: body ? JSON.stringify(body) : undefined }),
  del: <T = { status: string }>(path: string) => request<T>(path, { method: 'DELETE' }),
}

`

// tsBridge re-exports the handwritten satellites. Two rules keep the api ⇄ api-manual
// cycle safe, stated in both file headers: nothing but this file may import api-manual,
// and api-manual must never reference `api` at module top level (only inside bodies).
const tsBridge = `import { manualDaffa } from './api-manual'

export { bytes, nodeQuery } from './api-helpers'
export * from './api-manual'

`

// tsInterface renders one component.
func tsInterface(c *Component) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", c.Name)
	for _, p := range c.Schema.Properties {
		name := p.Name
		if !tsIdentRe.MatchString(name) {
			name = fmt.Sprintf("%q", name)
		}
		opt := ""
		if !c.Schema.IsRequired(p.Name) {
			opt = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s\n", name, opt, tsType(p.Schema))
	}
	b.WriteString("}\n")
	return b.String()
}

var tsIdentRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// tsType renders a schema as a TS type expression.
func tsType(s *Schema) string {
	switch {
	case s == nil:
		return "unknown"
	case s.Ref != "":
		return s.Ref[strings.LastIndex(s.Ref, "/")+1:]
	case s.Free:
		return "unknown"
	case len(s.OneOf) > 0:
		arms := make([]string, len(s.OneOf))
		for i, a := range s.OneOf {
			arms[i] = tsType(a)
		}
		return strings.Join(arms, " | ")
	}
	switch s.Type {
	case "string":
		if len(s.Enum) > 0 {
			vals := make([]string, len(s.Enum))
			for i, v := range s.Enum {
				vals[i] = "'" + v + "'"
			}
			return strings.Join(vals, " | ")
		}
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	case "array":
		inner := tsType(s.Items)
		if strings.ContainsAny(inner, "|{ ") {
			return "(" + inner + ")[]"
		}
		return inner + "[]"
	case "object":
		switch {
		case s.AdditionalProps != nil:
			return "Record<string, " + tsType(s.AdditionalProps) + ">"
		case len(s.Properties) > 0:
			parts := make([]string, len(s.Properties))
			for i, p := range s.Properties {
				opt := ""
				if !s.IsRequired(p.Name) {
					opt = "?"
				}
				parts[i] = fmt.Sprintf("%s%s: %s", p.Name, opt, tsType(p.Schema))
			}
			return "{ " + strings.Join(parts, "; ") + " }"
		default:
			return "Record<string, unknown>" // map[string]any until somebody lifts it
		}
	}
	return "unknown"
}

var pathParamRe = regexp.MustCompile(`\{([a-zA-Z0-9_]+)\}`)

// tsMethod renders one daffa client method. The shape is deliberately rigid — name from
// `ts:`, path params as args in pattern order, then the body — because rigidity is what
// makes a migrated method byte-compatible with the handwritten one it replaces. Anything
// needing more (query params, splat args, streams) stays in api-manual.ts by design.
func tsMethod(op *Op) (string, error) {
	params := pathParamRe.FindAllStringSubmatch(op.Path, -1)

	var args []string
	for _, m := range params {
		typ := "string"
		for _, p := range op.PathParams {
			if p.Name == m[1] && len(p.Enum) > 0 {
				vals := make([]string, len(p.Enum))
				for i, v := range p.Enum {
					vals[i] = "'" + v + "'"
				}
				typ = strings.Join(vals, " | ")
			}
		}
		args = append(args, m[1]+": "+typ)
	}
	if op.Req != nil {
		args = append(args, "body: "+tsType(op.Req))
	}

	respType := "void"
	if op.Resp != nil && op.Status != 204 {
		respType = tsType(op.Resp)
	}
	if !op.RespDeclared && op.Status != 204 {
		return "", fmt.Errorf("openapi: %s declares ts:%q but no response type — a client method whose answer is untyped helps nobody", op.Pattern, op.TSName)
	}
	if op.Produces != "" {
		return "", fmt.Errorf("openapi: %s declares ts:%q but produces %s — streams and downloads stay handwritten", op.Pattern, op.TSName, op.Produces)
	}

	path := "'" + op.Path + "'"
	if len(params) > 0 {
		path = "`" + pathParamRe.ReplaceAllString(op.Path, "${$1}") + "`"
	}

	verb := map[string]string{"GET": "get", "POST": "post", "PUT": "put", "PATCH": "patch", "DELETE": "del"}[op.Method]
	if verb == "" {
		return "", fmt.Errorf("openapi: %s: no client verb for %s", op.Pattern, op.Method)
	}

	call := fmt.Sprintf("api.%s<%s>(%s", verb, respType, path)
	if op.Req != nil {
		call += ", body"
	}
	call += ")"

	sig := fmt.Sprintf("(%s)", strings.Join(args, ", "))
	line := fmt.Sprintf("  %s: %s => %s,\n", op.TSName, sig, call)
	// The one-arg arrow style matches the handwritten file; wrap long lines the way
	// prettier would so `pnpm build` and format checks see stable text.
	if len(line) > 102 {
		line = fmt.Sprintf("  %s: %s =>\n    %s,\n", op.TSName, sig, call)
	}
	return line, nil
}
