//go:build ignore

// Generates web/src/lib/caps.ts from the registry.
//
// The frontend needs the same namespace and the same bit for the same capability as the
// backend. Hand-maintaining a second copy of thirty-odd constants is a drift waiting to happen,
// and the way you find out is a button visible to someone who cannot press it — or worse,
// hidden from someone who can.
//
//	go generate ./internal/caps
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/Mnshahawy/daffa/internal/caps"
)

func main() {
	var b strings.Builder

	b.WriteString(`// Code generated by internal/caps/gen.go — DO NOT EDIT.
//
// Run: go generate ./internal/caps

/**
 * A capability is one bit within one NAMESPACE — a functional area that carries its own mask.
 *
 * The flat mask this replaces was a single number, and it was running out. Each area now has
 * its own mask — 31 bits, the width of the INTEGER column that stores it — and a new area
 * costs one line of Go, so no area should ever be near its ceiling.
 */
export const Ns = {
`)
	for _, a := range caps.Namespaces {
		b.WriteString(fmt.Sprintf("  /** %s */\n", a.Description))
		b.WriteString(fmt.Sprintf("  %s: '%s',\n", tsName(string(a.NS)), a.NS))
	}

	b.WriteString(`} as const

export type Namespace = (typeof Ns)[keyof typeof Ns]

/** What a user or a role holds: one mask per namespace. Absent means zero. */
export type CapSet = Partial<Record<Namespace, number>>

export interface Cap {
  readonly ns: Namespace
  readonly bit: number
}

export const Cap = {
`)

	for _, d := range caps.All {
		b.WriteString(fmt.Sprintf("  /** %s */\n", d.Description))
		b.WriteString(fmt.Sprintf("  %s: { ns: Ns.%s, bit: %d },\n",
			tsName(d.Name), tsName(string(d.NS())), uint32(1)<<uint(d.Bit())))
	}

	b.WriteString(`} as const satisfies Record<string, Cap>

export type CapValue = (typeof Cap)[keyof typeof Cap]

/**
 * Does this set carry that capability?
 *
 * A cap with no bit is never satisfied, mirroring the server: a check written against something
 * that does not exist denies rather than admits.
 *
 * DO NOT rewrite the test as ` + "`(mask & cap.bit) !== 0`" + `. It looks like the obvious spelling and it
 * is wrong, because JavaScript's bitwise operators coerce BOTH operands to 32-bit signed
 * integers before doing anything. A capability above bit 31 therefore becomes literally zero:
 *
 *     4294967296 | 0   // bit 32  ->  0
 *     mask & 0         // ->  0, so the check can NEVER pass. For anyone. Including an admin.
 *
 * That shipped, back when the mask was flat: Resource Monitors appeared in the nav (monitors.view
 * was bit 31, which survives by accident because the sign bit is still a bit) and its editor did
 * not (monitors.edit was bit 32, which does not) — so an administrator holding every capability
 * in the registry was told they could not create a monitor.
 *
 * Namespacing means no area is anywhere near bit 31 today. That is not a reason to use the
 * broken operator; it is a reason the bug would take even longer to find next time.
 */
export function hasCap(set: CapSet | undefined, cap: CapValue): boolean {
  if (!set || !cap?.bit) return false
  return (BigInt(set[cap.ns] ?? 0) & BigInt(cap.bit)) !== 0n
}
`)

	if err := os.WriteFile("../../web/src/lib/caps.ts", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "caps: writing caps.ts:", err)
		os.Exit(1)
	}
	fmt.Printf("caps: wrote web/src/lib/caps.ts (%d capabilities in %d areas)\n",
		len(caps.All), len(caps.Namespaces))
}

// compound spells out the wire names that are more than one word, so the generated constant
// reads like the Go one (GitCredsView) instead of like a typo (GitcredsView). The wire name is
// the canonical form and stays lowercase; this is only about the label.
var compound = map[string]string{"gitcreds": "GitCreds"}

// containers.exec → ContainersExec
func tsName(name string) string {
	var out strings.Builder
	for _, part := range strings.Split(name, ".") {
		if c, ok := compound[part]; ok {
			out.WriteString(c)
			continue
		}
		out.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return out.String()
}
